
spring:
 datasource:
   url: jdbc:mysql://localhost:3306/tracking
   username: aashutosh
   password: Bank@123
   driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
